apiVersion: apps/v1 
kind: Deployment
metadata:
  name: det-matrix 
  namespace: s76457
  labels:
    app: det-matrix
spec:
  revisionHistoryLimit: 3
  replicas: 1 
  selector:
    matchLabels:
      app: det-matrix
  template:
    metadata:
      labels:
        app: det-matrix
    spec:
      containers:
      - name: app
        image: tensorflow/tensorflow:latest-devel-py3
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           git clone https://github.com/pallavimitra/det-matrix-kubernetes;
           cd det-matrix-kubernetes;
           pip install -r requirements.txt;
           python main.py;
        ports:
        - containerPort: 8080
          protocol: TCP
