apiVersion: apps/v1 
kind: Deployment
metadata:
  name: inverse-matrix 
  namespace: s76457
  labels:
    app: inverse-matrix
spec:
  revisionHistoryLimit: 3
  replicas: 1 
  selector:
    matchLabels:
      app: inverse-matrix
  template:
    metadata:
      labels:
        app: inverse-matrix
    spec:
      containers:
      - name: app
        image: tensorflow/tensorflow:latest-devel-py3
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           git clone https://github.com/pallavimitra/inverse-matrix-kubernetes;
           cd inverse-matrix-kubernetes-master;
           pip install -r requirements.txt;
           python main.py;
        ports:
        - containerPort: 8080
          protocol: TCP
