apiVersion: v1
kind: Service
metadata:
  name: inverse-matrix-service
  labels:
    app: inverse-matrix
spec:
  ports:
    - port: 8080
  selector:
    app: inverse-matrix
  type: LoadBalancer
